### ISSUE TITLE
Missing gui style "red_slot_button_style" for hidden items

### ISSUE THREAD

**Issue by 321freddy** [npo6ka/FNEI#12]
Got this issue on my attach notes mod: https://github.com/321freddy/attach-notes/issues/4

I nailed it down to an issue in the FNEI code:
In libs/utils_style.lua you set the style for hidden items to "red_slot_button_style".
This style is not defined anywhere (or maybe a typo?).

Please fix. Thanks in advance :)

**Comment by npo6ka** [comment]
Thanks for your feedback, I will try to fix this problem soon

**Comment by npo6ka** [comment]
fixed in 0.0.17 version
