### ISSUE TITLE
Nuclear Samples in the Pyanodon Fusion Energy Mod won't display recipe

### ISSUE THREAD

**Issue by ChurchOrganist** [npo6ka/FNEI#17]
Hi there,

A few of us started a Pyanodon Server recently, and we have just got to starting the Production Science research chain. 

The Nuclear Sample product which is part of this is not displaying a recipe in FNEI - I don't know whether this is something in FNEI mod or in Pyanodon's - I shall be reporting this also in Pyanodon's Github Issues - perhaps you could communicate to work out why?

Pyanodon's Fusion Energy Github is here.......
https://github.com/pyanodon/pyfusionenergy/issues/1

**Comment by npo6ka** [comment]
fixed in 0.1.6
