### ISSUE TITLE
Backspace doesn't work in inserter capacity override input

### ISSUE THREAD

**Issue by coderpatsy** [npo6ka/FNEI#18]
Game version: 0.16.36 (build 36253, win64, steam)
FNEI version: 0.1.5

When FNEI is on, pressing backspace in the inserter capacity override input doesn't do anything, both with and without text selected. Delete still works as expected, as does typing numbers. Other inputs don't seem to be affected.

Backspace works fine if FNEI isn't on.

**Comment by npo6ka** [comment]
Thanks for the feedback.
I did not understand the essence of the problem, could you describe your problem in more detail.

**Comment by coderpatsy** [comment]
When you click on an inserter with a stack capacity bonus, there's an input to change the max items it can pick up at once. When I have FNEI on, pressing the backspace key on a keyboard doesn't delete characters in that input, unless I press and hold the key.

[Here is a screencap showing this in action.](https://user-images.githubusercontent.com/13140934/38217216-bba538ac-368a-11e8-9da3-70c9e9062a49.jpg) I am currently clicking the backspace key, and it is not deleting the 2.

To be clear, the On Screen Keyboard functions identically to any other keyboard, I just used it for showing this weird bug.

**Comment by npo6ka** [comment]
Hmm.. I think this problem applies not only to my mod. It is necessary to write about this to the developers of the game.

**Comment by npo6ka** [comment]
fixed in 0.1.6

**Comment by npo6ka** [comment]
The game also fixed this error: https://forums.factorio.com/viewtopic.php?f=11&t=59354
