### ISSUE TITLE
Немного увеличить ширину кнопки с текстом «использование»

### ISSUE THREAD

**Issue by dima74** [npo6ka/FNEI#22]
Сейчас текст не влезает (а справа от кнопки как раз есть немного места):
![image](https://user-images.githubusercontent.com/6505554/40845874-9d0a2bea-65c0-11e8-8caf-81ffc6bbc710.png)

Спасибо за мод!

**Comment by npo6ka** [comment]
Исправил, в 0.1.7 всё должно быть нормально.
