### ISSUE TITLE
Настройка для скрытия рецептов заполнения/опустошения бочек

### ISSUE THREAD

**Issue by dima74** [npo6ka/FNEI#23]
Будет здорово добавить настройку для скрытия рецептов заполнения/опустошения бочек, возможно включённую по умолчанию

**Comment by npo6ka** [comment]
Такая возможно уже есть, в настройках во вкладке крафтинг категорий, найди завод отвечающий за это это и отключить его ПКМ.

**Comment by dima74** [comment]
О, да, действительно, получилось, спасибо.

Может отключить эти рецепты по умолчанию?

**Comment by npo6ka** [comment]
это не единственное что надо отключить, и каждый мод может добавлять свои машины для этого. Тут сложно угадать что отключать. Иногда людям необходимо знать что есть такая возможность, поэтому я оставил эту вещь опциональной
