### ISSUE TITLE
Unknown sprite "recipe/stone"

### ISSUE THREAD

**Issue by dima74** [npo6ka/FNEI#27]
На сервере [beardedsnails](https://vk.com/factorio_server_beardedsnails) при игре с [данными модами](https://yadi.sk/d/hX2BgUW35h9aSg) иногда возникает ошибка 

    Unknown sprite "recipe/stone"

![image](https://user-images.githubusercontent.com/6505554/45254164-6bc21c00-b37c-11e8-9d6c-e2bf07c15ec5.png)

К сожалению, не обладаю подробной информацией о данной ошибке, но я подумал что будет здорово если её зарепортить

---

Спасибо за мод!

**Comment by npo6ka** [comment]
Спасибо за отзыв. Странно, я не смог повторить данную ошибку у себя. Возможно это связано с другой ошибкой о которой было сказано ранее на мод портале. В следующем обновлении я сделаю чтоб игра не крашилась при подобного рода ошибках, а просто писала предупреждение в чат.

**Comment by npo6ka** [comment]
Да, похоже проблемы одинакового характера: https://mods.factorio.com/mod/FNEI/discussion/5b836bb831ef02000a57bf1e
