### ISSUE TITLE
Missing searchresults

### ISSUE THREAD

**Issue by bisam** [npo6ka/FNEI#3]
Hi, thanks for your mod :)

I am using this modpack: [https://forums.factorio.com/viewtopic.php?f=95&t=43759](https://forums.factorio.com/viewtopic.php?f=95&t=43759) (It mainly uses bobs&angles) with the latest experimental version of factorio and found an issue with the search function.

I tried searching for Sulfuric Waste and entered "sulfur". Everything except Sulfuric Waste came up. If i entered "waste", sulfuric waste was in the results.

**Comment by npo6ka** [comment]
Thanks for your issue.
Api factorio do not allow searching for localized names of items, so I had to implement at least such a search. At the current moment, the search takes place according to the names of the objects assigned by the author, for example, "iron-plate", "-" and other symbols are ignored. This causes a lack of items when searching. Sometimes the auther call their items "mod-sulf" and not "mod-sulfur".

**Comment by npo6ka** [comment]
https://forums.factorio.com/viewtopic.php?p=98711#p98711

**Comment by npo6ka** [comment]
I found a way to realize this, but it will not be so convenient. Will be implemented in the new version 0.1.0.

**Comment by npo6ka** [comment]
I found a way to realize this, but it will not be so convenient. Will be implemented in the new version 0.1.0.
