### ISSUE TITLE
use mod-gui to organize UI elements

### ISSUE THREAD

**Issue by JonasJurczok** [npo6ka/FNEI#33]
In [FFF 174](https://www.factorio.com/blog/post/fff-174) wube anounced `mod_gui` to standardize mod UIs.

In [this bugreport](https://mods.factorio.com/mod/Todo-List/discussion/5c7ba62ec3dad0000bfe86ed) we found out that the overall space for mods decreased with 0.17.

Question: can you also move to mod_gui as a base for FNEI?
This would bring it in line with other mods and hands ordering of frames back to Factorio.

I wanted to provide a pull request but don't have the time to dig really into your code.

Thanks,
Jonas

**Comment by npo6ka** [comment]
Thanks for your feedback. Honestly, I do not quite understand the essence of your problem, but I can try to use mod_gui. I think the drop-down list of the FNEI mod will not be able to match the style described in mod_gui. I will check how it works in the near future.

**Comment by JonasJurczok** [comment]
The problem we discovered is that rendering of mods breaks if all the mods
combined use more space than the screen provides. Specifically some things
just shrink randomly.

Mod GUI was introduced to separate mod guis by meaning and unify the style
(buttons at the top, frames to the left).

You could say mod GUI provides a framework/canvas for your mod to sit on.

One thing mod GUI does is that open windows (put on the frame flow) are not
stacking vertically and thus provoking the rendering problem.

Instead they stack horizontally. This makes them spread out to the right.
Then the user can pick which one he wants to have open at the moment.

**Comment by npo6ka** [comment]
Well, I'll see how it works with my mod when I have time.

**Comment by npo6ka** [comment]
Fixed in next version!

**Comment by JonasJurczok** [comment]
Awesome, thanks
