### ISSUE TITLE
Bug report: FNEI saved around 2 GB of data in global

### ISSUE THREAD

**Issue by Bilka2** [npo6ka/FNEI#34]
Please see https://forums.factorio.com/viewtopic.php?f=23&t=67601. The script.dat of that save is 2.6GB, largely taken up by your mod. The save is unplayable due to this. I would guess that this is due to some kind of interaction of the mods in that particular save. I hope you kind find what causes this and fix it so that no future saves become unplayable.

**Comment by npo6ka** [comment]
Thanks for your feedback, it's nice to get feedback from the game developer)
These crazy players have thrown too many conflicting mods. Fnei under the new version is very unstable, I will definitely correct this error.
P.S. You did not discuss the idea of introducing a function similar to my mod? Sometimes it would be useful to know what can be obtained from any prototype.

**Comment by jeinstei** [comment]
I'm just wondering if this is the same issue as described here, in the new version? https://mods.factorio.com/mod/FNEI/discussion/5e791f11936116000e27421a

This seems like a relatively straightforward fix. I've never worked on a mod, but maybe I'll take a look....

**Comment by npo6ka** [comment]
Need to keep a reference to the recipe object instead of the recipe name. I understand that the mod is not ideal, but unfortunately I do not have enough time and desire to completely rework this mod.

**Comment by jeinstei** [comment]
Of course -- I'll see how far I can get with it. I was going to try and clean up some functions for speed as well, so maybe it will end up actually being useful at some point. Definitely appreciate the work in it

**Comment by npo6ka** [comment]
Deprecated
