### ISSUE TITLE
The Todo List mod loses it's buttons when FNEI is loaded

### ISSUE THREAD

**Issue by ChurchOrganist** [npo6ka/FNEI#35]
Hi there,
I've just started a Yuoki playthrough on one of my servers.

We would very much like to use FNEI in our playthrough, but have discovered that there is a clash with Todo List in that the buttons at the bottom of Todo List disappear when FNEI is active.

No idea what's causing this - I shall be contacting the Todo List maintainer to advise of the situation.

Hopefully the two of you can come up with a solution :)

Regards
Michael

PS you can reach hime at https://github.com/JonasJurczok/factorio-todo-list

**Comment by npo6ka** [comment]
Thank you for your feedback. Fixed in next version!
