### ISSUE TITLE
Recipe look up error

### ISSUE THREAD

**Issue by EPSIL0N** [npo6ka/FNEI#36]
Using version 0.2.1 when ever I left click an icon or click the craft option for the default search fnei disappears and i have to press Ctrl E twice to get it back.

**Comment by npo6ka** [comment]
Thank you for your feedback. Would you please attach your save file here? I will check what could be the problem.

**Comment by EPSIL0N** [comment]
[FNEI test 1.zip](https://github.com/npo6ka/FNEI/files/2975687/FNEI.test.1.zip)

Sorry for the delay, I was attempting to rebuild my mod list slowly to see if it was just an issue of excessive content.

First started being unable to look up craft recipes when I added prospector to the larger set and after a bit of testing I noticed that if I look up the uses for prospector (the pseudo item) FNEI will disappear if i try to view particular uses for it.

I think in the small set of the test1 save it won't let you view use 8.

**Comment by npo6ka** [comment]
Check new version fnei 0.2.2. May be this problem fixed...

**Comment by EPSIL0N** [comment]
I think the save was made with that version of fnei.

**Comment by npo6ka** [comment]
Thanks for the help in the development of the mod, I will try to correct this error.

**Comment by EPSIL0N** [comment]
Were you able to find the one item behaving oddly? I forgot if it was 8 or if 8 was the last working one when scrolling upwards.

Glad to be of help when I can, can't play with ridiculously bloated modlists without FNEI to remember the recipes for us.

**Comment by npo6ka** [comment]
I found what the problem was, i can just add a check to this place and everything will work, but I would like to find out what is written in this mods that could cause such an error.

**Comment by npo6ka** [comment]
Fixed in next version.
