### ISSUE TITLE
Factorio crashing when clicking on an item icon

### ISSUE THREAD

**Issue by themroc5** [npo6ka/FNEI#38]
Factorio version: 0.17.20
Image: http://factorio.gap.io/fneicrash.jpg

When I click on any icon Factorio crashes as shown in the image. 

- This happens with every item, not only with Pyanodon items
- This happens in single and in multiplayer. 
- On two different computers playing the game with the mods this happened. However, on a third computer it worked fine.

I'm not entirely sure this bug report belongs here. I'll post this on the forums too.

[mod-settings.zip](https://github.com/npo6ka/FNEI/files/3010038/mod-settings.zip)
[mod-list.zip](https://github.com/npo6ka/FNEI/files/3010047/mod-list.zip)

**Comment by themroc5** [comment]
This actually might be fixed already: https://forums.factorio.com/viewtopic.php?f=30&t=68533

**Comment by Seyeght** [comment]
I am getting this issue without having anything pinned in Helmod, and my monitor is a standard 16:9, at 100% UI scaling.

**Comment by Seyeght** [comment]
Game version: 0.17.20
FNEI: 0.2.3
Crash log: https://pastebin.com/nF0TuG4p

**Comment by npo6ka** [comment]
These are problems of the game, you need to throw off similar errors to the developers of the game.
Perhaps the new version has already fixed it?

**Comment by themroc5** [comment]
Indeed the 0.17.21 fixes it.
