### ISSUE TITLE
[Suggestion] Add mod information

### ISSUE THREAD

**Issue by bisam** [npo6ka/FNEI#4]
Would it be possible to add information regarding which mod a certain item belongs to?

**Comment by npo6ka** [comment]
Hm... I think it's impossible. I will check it.

**Comment by npo6ka** [comment]
Unfortunately, I did not find a way to do this. If you know how to get this information, please write here or on the forum.

**Comment by npo6ka** [comment]
I found a way to realize this, Will be implemented in the new version 0.1.0.
