### ISSUE TITLE
Seems broken with the latest factorio .17 update

### ISSUE THREAD

**Issue by florianschanda** [npo6ka/FNEI#45]
The FNEI button is there, but clicking it will make it disappear. On my pyanodon savegame it just crashed.

Should be easy to reproduce... Just start a fresh game with just FNEI and click the button.

**Comment by ChurchOrganist** [comment]
I've also experienced problems with 0.17.56 FNEI this is with Yuoki's mods. FNEI simply prints recipe_name in the title bar. Also see this in the mod portal discussion area.......
https://mods.factorio.com/mod/FNEI/discussion/5d279a2e464742000cf0c9d3

**Comment by kurtzilla** [comment]
It was suggested in the factorio forums that removing line 240 from the code fixes the issue. Someone has also posted a fixed zip file at https://mega.nz/#!LGoEUCAS!5lCUe_j5kjRbIAiJcFfs3SIHJKTm4Afwx1mPNrgXt78

**Comment by Akirami** [comment]
> It was suggested in the factorio forums that removing line 240 from the code fixes the issue. Someone has also posted a fixed zip file at https://mega.nz/#!LGoEUCAS!5lCUe_j5kjRbIAiJcFfs3SIHJKTm4Afwx1mPNrgXt78

Works well, thanks.

**Comment by twothe** [comment]
Same issue here: server won't start anymore with FNEI enabled.

**Comment by npo6ka** [comment]
Fixed in next version.
