### ISSUE TITLE
Search has disappeared from the Standard fluid filter.

### ISSUE THREAD

**Issue by ChurchOrganist** [npo6ka/FNEI#51]
The search box has disappeared from the Standard Search Fluid Filter dialogue.

I'm playing Pyanodon atm and the search box is pretty important due to the mind-boggling number of fluids in the mod.

Any chance of restoring it??

**Comment by npo6ka** [comment]
Could you attach a screenshot of how it looks now?

**Comment by ChurchOrganist** [comment]
![FNEILiquids](https://user-images.githubusercontent.com/1997050/79696684-2c58f280-8276-11ea-9735-c929a45daf95.PNG)
There ya go :)

**Comment by npo6ka** [comment]
This is the gui (choose-elem-button) of the factorio game itself, I call this gui so that we can search by localized names. It is necessary to write to the developers of the game about this shortfall.

**Comment by ChurchOrganist** [comment]
OK thanks - I'll put a bug report in - any hint as to where it is located in the Factorio files??

**Comment by npo6ka** [comment]
Gui fluid choice(choose-elem-button) has no search field.

**Comment by ChurchOrganist** [comment]
I'll carry on using the FNEI search for fluids.

Presumably the devs feel that the number of fluids in vanilla doesn't justify a search box.

Something must have changed, however, this is the same fluid GUI from Factorio 0.18.12
![FNEILiquids_0-18-12](https://user-images.githubusercontent.com/1997050/80459602-7ef77600-892a-11ea-9cf4-152920f82beb.PNG)

I'll take it up with the devs.

**Comment by npo6ka** [comment]
This should be fixed in future versions of the factorio.
https://forums.factorio.com/viewtopic.php?f=30&t=84907
