### ISSUE TITLE
GUI clash with YARM

### ISSUE THREAD

**Issue by RalfJung** [npo6ka/FNEI#53]
When having both YARM and FNEI installed, things don't look great as the very wide YARM menu and the FNEI button end up next to each other:

![Screenshot_20200501_103406](https://user-images.githubusercontent.com/330628/80793611-e23a1000-8b97-11ea-8b6b-a9c06ab7187d.png)

Is there anything that can be done about that?

**Comment by npo6ka** [comment]
Thanks for your feedback, Fixed in new version!

**Comment by RalfJung** [comment]
Confirmed, thanks. :-)
