### ISSUE TITLE
New update breaks mod.

### ISSUE THREAD

**Issue by michaelkrymski** [npo6ka/FNEI#57]
Failed to load mods: Error while loading gui-style prototype "default" (gui-style): Parent style not found: fnei_recipe_green_tech_button. 

New factorio gui update is the cause of it. New icons etc.

Edit: I was on Factorio 0.18.27.

**Comment by Crow08** [comment]
fixed in #59 ;)

**Comment by excavador** [comment]
@Crow08 can we receive update of the mod for installation from Factorio?

**Comment by Crow08** [comment]
npo6ka, the mod owner, has to approve and publish the changes. Then you can update the mod through the factorio mod integration.

**Comment by excavador** [comment]
@npo6ka кати на прод :)

**Comment by npo6ka** [comment]
Fixed, Thanks Crow08!
