### ISSUE TITLE
parent style gone/renamed

### ISSUE THREAD

**Issue by McAndersDK** [npo6ka/FNEI#58]
https://github.com/npo6ka/FNEI/blob/39ec10d3adfbeeb3a80aa7039f9105be4d6368b5/prototypes/recipe_styles.lua#L277

green_slot_button is not in the default anymore.

Maybe it's renamed to just slot_button?

**Comment by Crow08** [comment]
fixed in #59 ;)

**Comment by npo6ka** [comment]
Fixed, Thanks Crow08!
