### ISSUE TITLE
Remove items from hotbar

### ISSUE THREAD

**Issue by rmillet42** [npo6ka/FNEI#60]
Factorio: 0.18.26 (linux)
FNEI: 0.3.2

Hello,

I want to remove items from the hotbar.

The first issue is that "`ALT` key + click" does not work, it seems to be "`ALT GR` key + click" that is working. Is that because I am using linux or is the description incomplete?

The second issue with "`ALT GR` key + click": after loading a game, without clicking anywhere else in FNEI before, it triggers an error:

```
Error while running event FNEI::on_gui_click (ID 1)
__FNEI__/core/Debug.lua:56: attempt to index global '__DebugAdapter' (a nil value)
stack traceback:
	__FNEI__/core/Debug.lua:56: in function 'print_to_console'
	__FNEI__/core/Debug.lua:76: in function 'error'
	__FNEI__/scripts/custom_events.lua:69: in function 'invoke'
	__FNEI__/scripts/events.lua:74: in function <__FNEI__/scripts/events.lua:71>
```

Thank you.

**Comment by npo6ka** [comment]
Second problem fixed.
I tried to push various options of the key, both options work (under windows). Apparently this is the specifics of Linux.
