### ISSUE TITLE
FNEI does not display the ingredients temperature range

### ISSUE THREAD

**Issue by clampi** [npo6ka/FNEI#61]
Recipe ingredients support more than a single value .temperature. See [Ingredient properties](https://lua-api.factorio.com/latest/Concepts.html#Ingredient). Some time back I remember FNEI supported the temperatures for ingredients, now it doesn't.

Here is some code that will bring back that functionality
__FNEI__/scripts/recipe/gui.lua, ~line 479
```lua
  -- add temperature for fluid
  local function is_number(value) return "number" == type(value) end
  local function is_finite(value) return is_number(value) and value-(value-1) == 1 and value-(value+1) == -1 and -math.huge ~= value and math.huge ~= value end
  
  if element.type == "fluid" and Settings.get_val("show-temperature-of-fluids")  then
	if element.temperature then -- product
		loc_str = {"", loc_str, " (" .. element.temperature .. "°)"}
	elseif element.minimum_temperature and not is_finite(element.maximum_temperature) then -- ingredient
		loc_str = {"", loc_str, " ( ≥" .. element.minimum_temperature .. "°)"}
	elseif element.maximum_temperature and not is_finite(element.minimum_temperature) then -- ingredient
		loc_str = {"", loc_str, " ( ≤" .. element.maximum_temperature .. "°)"}
	elseif element.minimum_temperature and element.maximum_temperature then -- ingredient; must be after each of the single temperature value test
		if element.minimum_temperature == element.maximum_temperature then
			loc_str = {"", loc_str, " (" .. element.minimum_temperature .. "°)"}
		else
			loc_str = {"", loc_str, " ([" .. element.minimum_temperature .. ", " .. element.maximum_temperature .. "]°)"}
		end
	end
  end
```
Some points about the code.
- Factorio seems to always return both `element.minimum_temperature` and `element.maximum_temperature`, but when the temperature is not defined in prototype, it returns the lowest/greatest number that can still be represented on a double. It is not `NaN` (math.huge), but a number very large. The test `value-(value-1) == 1 and value-(value+1) == -1` excludes numbers that are not huge enough such that n-1 or n+1 overflow.
- The test for both temperatures present must be placed after the single temperatures test, such that the above tests will correctly identify the cases where min_temp/max_temp are not really defined in the prototype.
- The test for equal temperatures is needed for a nice output, instead of an interval.

Attached some snapshots of recipes with temperature restricted fluid ingredients, with the above code changes.
![FNEI_fluid_ingredients_temperature1](https://user-images.githubusercontent.com/10470629/83111386-2c49df00-a0cd-11ea-9870-a3bfb5bbb264.png)

![FNEI_fluid_ingredients_temperature2](https://user-images.githubusercontent.com/10470629/83111427-3d92eb80-a0cd-11ea-84d8-70e1252f2303.png)

**Comment by npo6ka** [comment]
Thank you for your feedback, I will try to fix this problem in the next updates!

**Comment by npo6ka** [comment]
a1bc6005837795ece12524bf1b030be80f95cf50
