### ISSUE TITLE
GUI lag while Improved Research Queue is installed

### ISSUE THREAD

**Issue by dbeckwith** [npo6ka/FNEI#66]
Some users of my mod [Improved Research Queue](https://mods.factorio.com/mod/sonaxaton-research-queue) have [noticed](https://mods.factorio.com/mod/sonaxaton-research-queue/discussion/5fd94550d69f4cb8d2f8e161) that when both mods are enabled, FNEI lags quite a bit when doing anything in the GUI. Any idea why that might be? My mod doesn't add any item prototypes or anything like that, it's just a GUI for the research queue. Maybe something GUI-related your mod is doing when you click something? Maybe [`gui_iterate`](https://github.com/npo6ka/FNEI/blob/master/scripts/gui.lua#L27) is iterating through my mod's GUI somehow?

**Comment by npo6ka** [comment]
Is this problem still relevant?

**Comment by Curry** [comment]
I believe so, I am currently getting the same performance issue with Improved Research Queue and FNEI enabled. 
FNEI v0.4.1
sonaxaton-research-queue v0.4.21

As mentioned, clicking/interacting with anything in the FNEI GUI causes mini-lag spikes. Disabling Improved Research Queue does fix the issue.

**Comment by IIInitiationnn** [comment]
Can confirm this is still an issue.

**Comment by npo6ka** [comment]
Many GUIs have been created. FNEI searches all GUI elements to find the required components. A check has been added to ensure that the search occurs only in fnei gui and the problem is fixed. 17899f098a18c0165a5019de5bd7e536c9b6d35c
