### ISSUE TITLE
searching in other languages not working?

### ISSUE THREAD

**Issue by CurlyFlow** [npo6ka/FNEI#67]
Hey, im using latest version on factorio 1.1.30.
I know it says it cant search for translated stuff, but why?

I wonder why searching is not working in other languages.

Let me give you an example.

If i search for lead i find blei (german for lead)
But i cant search for blei... why is that so? I mean its correctly translated and shown, why it cant search for the translated name?

![1](https://user-images.githubusercontent.com/43281991/112732268-3af56280-8f39-11eb-9819-33ecbb876e6a.jpg)
![2](https://user-images.githubusercontent.com/43281991/112732305-69733d80-8f39-11eb-9406-df0ccc509b83.jpg)

**Comment by npo6ka** [comment]
This is a known issue. Missing searchresults #3

**Comment by npo6ka** [comment]
Use default search(Standardsuche) tab in your case!

**Comment by CurlyFlow** [comment]
May i know why you dont want / cant fix that?

> Use default search(Standardsuche) tab in your case!

Is that the same like the FNEI?

**Comment by npo6ka** [comment]
You can read about it here: https://github.com/npo6ka/FNEI/issues/3

> Is that the same like the FNEI?

Default search working on the game mechanics factorio. This allow you to search items/fluid by localized names.

**Comment by CurlyFlow** [comment]
Thanks.

I wonder how helmod search for BOTH english and localized names then?
<img width="1132" alt="12" src="https://user-images.githubusercontent.com/43281991/112980430-2ba12f80-915a-11eb-974b-fb6b5a2894a0.png">

The "standard suche" is complete useless. (too complicated) Cant you put a search bar there like on the FNEI search?

Maybe we can ask helmod how he did it? Its working perfectly, but he is unable (i dont know if he dont want or cant) to fix the esc problem xD (which works in FNEI) 

FNEI - translated names not working
helmod - esc opens main menue 

Dont get me wrong, i have no problem typing wood instead of holz, but i cant remember the whole special stuff from bobs and angels and exploration... you know... thats why it would be a really nice thing for all non english speakers to have this working.
