### ISSUE TITLE
Show Hidden Recipes Setting Default

### ISSUE THREAD

**Issue by KiwiHawk** [npo6ka/FNEI#69]
Setting "Show hidden recipes" defaults to true. Can you please change this to be false by default?

The hidden flag is used by mods to disable recipes that can not be accessed.

There is now a recipe flag Hidden From Player Crafting. These recipes should still be shown. Because of this, it's easy for mods to differentiate between disabling a recipe entirely (hidden) and hiding the recipe from the player's crafting menu to prevent clutter or confusion (hidden from player crafting).

https://lua-api.factorio.com/latest/LuaRecipePrototype.html#LuaRecipePrototype.hidden_from_player_crafting

**Comment by npo6ka** [comment]
3d754ff8a5b834ece10ac2c3803e43d45393894b
