### ISSUE TITLE
Add ability/ui to change item categories

### ISSUE THREAD

**Issue by FlashFire1** [npo6ka/FNEI#70]
When playing with a lot of mods or even just mods that both try to add their own categorising, you start to get a lot of categories that only have a few items in them and you have to click through them all to find what you want (both in FNEI panel and standard crafting menu).

I was looking for a mod that allowed me to change the categories and couldn't find one so was thinking I might have to ask someone to build it from the ground up (I could try but I haven't worked with Lua before so would need to learn first), when I realised that FNEI already has a similar panel and is used by people who have a lot of extra items added by mods so implementing this into FNEI would make a lot of sense.

**Comment by npo6ka** [comment]
Unfortunately, I won't be able to help with this issue.
