### ISSUE TITLE
Translate into Ukrainian language

### ISSUE THREAD

**Issue by MetenBouldry** [npo6ka/FNEI#72]
[controls]
pressed-fnei-gui-key=FNEI головна конопка
pressed-fnei-back-key=FNEI кнопка назад
[fnei]
FNEI=FNEI
ingredients=Інградієнти
results=Результат
made-in=Робиться в
technology=Технології
left=зліва
top=зверху
center=По центру
previous-key=Минулий рецепт
next-key=Наступний рецепт
page=Сторінка
handcraft=Ручний крафт
left-eneble-click=Лівий клік, щоб активувати
right-disable-click=Правий клік, щоб деактивувати
default-search=Пошук за замовчуванням
fnei-search=FNEI пошук
category-search=Пошук по категоріям
non-admin-permission=Ви не маєте прав адміністратора
out-of-range=Значення за межами допустимих кордонів
use-only-attainable-technologies=Використовувати лише досягнуті технології
show-hidden-recipes=Показувати приховані рецепти
crafting-time=Час крафту
craft-time-in-building=Час крафту у цьому будинку
choose-item=Виберіть предмет
choose-fluid=Виберіть рідину
default-tab-desription=Пошук за доступними предметами/рідинами. Пошук за замовчуванням не налаштовується і не відображає прихованих елементів.
fnei-tab-description=Нелокалізований пошук. Елементи доступні для пошуку їх англійських імен. Пошук може відображати приховані/вимкнені елементи.
item-auto-craft=Автоматично відкривати "крафт" рецепти для вибраного предмета.
item-auto-usage=Автоматично відкривати рецепти "Використання" для вибраного предмета.
fluid-auto-craft=Автоматично відкривати "крафт" рецепти для вибраної рідини.
fluid-auto-usage=Автоматично відкривати рецепти "Використання" для вибраної рідини.
recipe=Крафт
usage=Використання
usage-for=Використання
recipe-for=Рецепт для 
crafting-category=Категорії крафта
main-settings=Головні
admin-settings=Для адмінів
need-show=Закривати FNEI коли інше вікно відкрито або натиснуто кнопку ESC
show-disable-recipes=Показувати вимкнені рецепти
show-hidden-items=Показувати приховані предмети
position=Позиція вікна мода
fnei-line-count=Кількість рядків з предметами у вкладці FNEI
detail-chance=Показувати повну інформацію про відсоток отримання предмета
focus-search=Фокус курсору на пошуковому полі при відкритті вікна мода
close-gui-when-tech-open=Закривати FNEI коли відкривається дерево технологій
show-craft-time-label=Показувати час крафту рецепту в будинках
show-the-same-recipes=Показувати однакові рецепти
show-temperature-of-fluids=Показувати температуру рідини якщо є
show-hotbar=Показувати хотбар мода
craftin-cat-msg=Якщо в деяких будівлях/категоріях дуже багато рецептів, ви можете перемикати їх тут.
show-disable-techs=Показувати вимкнені технології
last_button=Останні рецепти
fav_button=Вибране
alt-to-remove=Використовуйте alt + клік, щоб видалити рецепт
hotbar-last-line-num=Кількість рядків останніх відкритих рецептів у тултипі FNEI
hotbar-fav-line-num=Кількість рядків вибраних рецептів у тултипі FNEI
favorite-is-full=Список вибраних рецептів переповнений
tooltip-recipe=Рецепт
favorite-button=Додати в обране

**Comment by npo6ka** [comment]
Resolved 4fcd740517878db3951ee2ce56e48d7ecb6b0af3
Thanks for this)
