### ISSUE TITLE
FNEI Window mising (possibly opens off screen)

### ISSUE THREAD

**Issue by JoshHawley** [npo6ka/FNEI#73]
When I push the FNEI button, or the associated hotkey, the window does not appear. However, I suspect it is opening off screen for two reasons. 
1. I recently downgraded monitors (from 4k to 1080), and this seems likely to confuse window positions. 
2. The Factorio menu does not open on the first press of the escape key.

The following procedure seems to indicate that the window is opening.
1. Push escape many times until the factorio menu opens. This is to ensure that the FNEI window is not open, basically resets us to a known state. 
2. Push the FNEI button once. Window does not appear (or at least is not visible)
3. Push escape and notice that the Factorio menu does not open. 
4. Push escape a second time, and the Factorio menu will open.

**Comment by JoshHawley** [comment]
Update: 
I took my save to another machine that is still running at 4k, and the FNEI window does indeed show up on the far right. I was able to move it back to the left and then take it back to my (now) lower resolution machine. 

When the window opens, it would be good to do a position check to validate that it is in the viewable area.

**Comment by danbopes** [comment]
This same thing happened to me when I downgraded my monitor.

**Comment by npo6ka** [comment]
Fixed 3f645619ab974ef7429dfb32fa062610825cdb7a
