### ISSUE TITLE
Error from Loading a Savegame

### ISSUE THREAD

**Issue by Vystella** [npo6ka/FNEI#77]
Hi,
as you wrote in the Modportal, here is the answer.

Playing Factorio on german language.
But error happens too if i change to english.
Happens on evey savegame too.

So here is 1 Savegame attached. (The one with the lowest mods that are needed.)
[12401-F7.zip](https://github.com/user-attachments/files/17590369/12401-F7.zip)

Some Mods are needed and one mod i will attach too, bc isnt in the Modportal (some personal stacksizes and co.)
[Vysconfig_2.0.0.zip](https://github.com/user-attachments/files/17590372/Vysconfig_2.0.0.zip)

Thanks, Vystella

**Comment by npo6ka** [comment]
Fixed, you might be able to search for items in German using fnei search
